# TEMPORARY CONFIG FILE FOR SECURITY SCANNING TEST
# This file contains intentional fake secrets to test security scanning

# Database Configuration (UPDATED)
database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "updated_database_password_456"
  connection_string: "postgres://admin:newpass789@prod-db.example.com:5432/myapp"

# API Keys and Tokens (UPDATED)
api_keys:
  stripe_secret: "sk_live_51KjFm8NpX7cZ9qR3tY6vW2uE4fG8hI9jK0lM"
  stripe_public: "pk_live_51KjFm8NpX7cZ9qR3tY6vW2uE4fG8hI9jK0lM"
  sendgrid: "SG.updated_sendgrid_key_2024_abcdefghijk.rest_of_updated_key"
  twilio_sid: "AC9876543210fedcba0987654321abcdef"
  twilio_token: "updated_twilio_auth_token_2024_fedcba09"

# Cloud Provider Credentials (UPDATED)
aws:
  access_key_id: "AKIA4R5T6Y7U8I9O0P1Q"
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYUpdatedSecret2024"
  region: "us-east-1"

google_cloud:
  project_id: "my-gcp-project"
  private_key_id: "1234567890abcdef"
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7VvBz...
    (fake private key content for testing)
    -----END PRIVATE KEY-----
  client_email: "service-account@my-gcp-project.iam.gserviceaccount.com"
  client_id: "123456789012345678901"

# Social Media API Keys
social_media:
  twitter_consumer_key: "fake_twitter_consumer_key_1234567890"
  twitter_consumer_secret: "fake_twitter_consumer_secret_abcdefghijklmnopqrstuvwxyz"
  facebook_app_id: "1234567890123456"
  facebook_app_secret: "fake_facebook_app_secret_abcdefghijklmnopqr"

# Webhooks and Callbacks
webhooks:
  slack: "https://hooks.slack.com/services/T1234567/B1234567/fake_slack_webhook_token"
  discord: "https://discord.com/api/webhooks/123456789012345678/fake_discord_webhook_token"

# Encryption Keys
encryption:
  jwt_secret: "my_jwt_secret_key_for_testing_123456789"
  aes_key: "16_char_aes_key!"
  salt: "random_salt_value_for_hashing"

# Email Configuration
email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "noreply@company.com"
  password: "email_app_password_123"

# Certificate Information
certificates:
  ssl_cert_path: "/path/to/ssl/certificate.pem"
  ssl_key_path: "/path/to/ssl/private.key"
  ssl_passphrase: "ssl_private_key_passphrase_123"